detection:
  annotations_file: "data/data.json"
  img_dir: "data/"
  weights_path: "weights/detection_model.pth"
  checkpoint_path: "checkpoints/detection_model_checkpoint.pth"
  num_classes: 4 # 3 classes (fracture, old fracture, suspicious fracture) + background
  batch_size: 4
  num_epochs: 10
  learning_rate: 0.005
